### ISSUE TITLE
Push deletion event for comments when deleted / banned

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/commentron#63]
If a mod or creator deletes a comment, others in the live stream still sees it, it's only hidden for new viewers. We should push a delete event where the app will clean them up for active viewers.

**Comment by tzarebczan** [comment]
We also need to push them to internal apis for deletion in notifications

**Comment by tiger5226** [comment]
expect a new websocket message `removed` that will contain the comment that was removed.
