### ISSUE TITLE
Add`mentions` to comment item, to also be sent with comment notifications

### ISSUE THREAD

**Issue by tiger5226** [OdyseeTeam/commentron#73]
This is to support notifying users when they are mentioned in a comment.

**Comment by tzarebczan** [comment]
Consider how to handle spam / notifications for bigger channels

**Comment by kauffj** [comment]
![notif](https://user-images.githubusercontent.com/530774/134417654-e2988afd-a0d2-4a1b-9ed5-b5bdc4f732b1.png)

**Comment by tzarebczan** [comment]
Spoke to mark about this previously and we can pass a new param with claim ids as mentions, that way the UI doesn't have to store the full id in the message, and we don't have to parse it.

**Comment by tiger5226** [comment]
So when mentioned channels are passed with the create request, commentron will pipe that to sockety. This message type is called `mention` and you will get a sockety message if you are subscribed to the channel claim id, or if you are subscribed to the `mentions` sockety comment service. The latter is what internal-apis will use to create event notifications for users.
