### ISSUE TITLE
Bug? Some data is missing from "get_claim_comments".

### ISSUE THREAD

**Issue by GlobalGamer2015** [OdyseeTeam/commentron#88]
This is what I am getting for just my comment on my stream channel.
`{
                "comment": "ping",
                "comment_id": "14de74dd1414ff6a43f3740f5a2c32e64404fa816b5e7dbf9964e4fc59483f96",
                "claim_id": "795609bf7d148982e61c11b677c813eab16584a9",
                "timestamp": 1631894255,
                "signature": "e90c5591af1b486851e7e73fadd3734fef304d07db693d64972b12efa2a3aa834fa5b82ba589f1c3d88673b349313c51df4a2b1cc5468d8e122641fa13539d0b",
                "signing_ts": "1631894255",
                "channel_id": "b8fbd24ab4644148cfed022732c48677cf662047",
                "channel_name": "@GG2015",
                "channel_url": "lbry://@GG2015#b8fbd24ab4644148cfed022732c48677cf662047",
                "currency": "",
                "support_amount": 0,
                "is_hidden": false,
                "is_pinned": false,
                "is_fiat": false
            }`

The data that is missing are: is_creator, is_moderator, and is_global_mod.
Perhaps I am missing a parameter in the request?
This is my JSON body
`{
    "jsonrpc": "2.0",
    "id": "null",
    "method": "get_claim_comments",
    "params": {
        "claim_id": "795609bf7d148982e61c11b677c813eab16584a9",
        "page_size": 5,
        "is_channel_signature_valid": true,
        "visible": true
    }
}`

**Comment by tzarebczan** [comment]
Yep, it's not implemented yet. Covered under https://github.com/OdyseeTeam/commentron/issues/44
