### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/commentron#89]
We need to document the list of API calls along with what params are available, and how channel signing works for each one. 

The SDK has removed comment* from it's SDK and I've been getting such questions.

**Comment by vertbyqb** [comment]
This is very important in my opinion. Applications (or people) using the LBRY SDK can't comment with newer versions of the SDK, so they must communicate with the comment servers directly, which are undocumented, effectively making it impossible to comment if you're using a newer version of the SDK. This is the biggest thing holding back [FastLBRY Terminal](https://notabug.org/jyamihud/FastLBRY-terminal) from upgrading the SDK bundled with it. Either the comment server should be documented (this issue), comment commands should be re-added to the SDK, or (my favorite, but probably the hardest to implement) comments should be decentralized.

**Comment by tzarebczan** [comment]
We provided them with detailed instructions on how to integrate, and the apps are good reference points for now. 

This makes comments decentralized...not sure what you mean.

**Comment by tiger5226** [comment]
Filled out the ReadMe with the areas to review, and adding links to the examples, and the go playground link to get started using the Go API commentron supports.
