### ISSUE TITLE
Notification mail: Thank you for x likes and comments this year for creators to share with their fans

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/commentron#96]
Sorry if this is the wrong place for this.

YT is sending a number of likes and comments for the channel of the creator to share with their fans on Social Media and I think such a thing would be great for Odysee too. Here is a example how this looks like:

![youtube-thank you for likes-comments](https://user-images.githubusercontent.com/44294954/146229534-a9bb97db-5c19-4486-89a3-8cbbea2f6414.png)

**Comment by tzarebczan** [comment]
Thanks for the suggestion, but don't plan to do this this year. Maybe next!
